# GitHub Action for CakePHP with MySQL and Redis
# Tested with https://github.com/cakephp/app
# nuzul fikrie salam version for testing cakephp v3.10.18 test comment based on CI/CD with GitHub Actions
name: Testing CakePHP with MySQL
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  testsuite:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4']
    name: PHP ${{ matrix.php-version }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl, pdo_sqlite
        coverage: none

    - name: Composer install
      run: |
        composer update
        composer run-script post-install-cmd --no-interaction

    - name: Run PHPUnit Unit testing for app
      env:
        MAIL_HOST: smtp.mailtrap.io
        MAIL_USERNAME: b97cb857629c4e
        MAIL_PASSWORD: 69e83f96de9863
        MAIL_PORT: 2525
        MAIL_FROM: webmaster@eaglenavigator.com
      run: |
        cp config/app_local.example.php config/app_local.php
        vendor/bin/phpunit
      env:
        DATABASE_TEST_URL: sqlite://./testdb.sqlite

  coding-standard:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl
        coverage: xdebug
        tools: cs2pr, phpstan:1

    - name: Composer install
      run: composer install

    - name: Run PHP CodeSniffer
      run: vendor/bin/phpcs --report=checkstyle src/ tests/ | cs2pr

    - name: Run phpstan
      if: always()
      run: phpstan analyse src/ --level=7